version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://udin:udin@10.128.0.2:5432/rails_postgres_cloud_run_production

# "postgres://myuser:mypass@localhost/somedatabase"
